version: 3.1.{build}
image: Visual Studio 2015


configuration:
    - Release
    - Debug


build_script:
    - cd c:\projects\npptranslate\nppTranslateCS\
    - msbuild nppTranslateCS.sln /p:configuration="%configuration%"



